-- Batch import of pigments
INSERT OR IGNORE INTO pigments (name) VALUES
('Blanc de titane'),
('Caput Mortuum'),
('Cendre d''olivier'),
('Cendre de châtaignier'),
('Cendre de cyprès'),
('Cendre de hêtre'),
('Cendre de platane'),
('Cochenille'),
('Cochenille du Mexique'),
('Feuille d''or'),
('Fusain'),
('Fusain / Sinopia'),
('Indigo Baphicacanthus'),
('Indigo de Kanagawa'),
('Indigo de la Roque d''Anthéron'),
('Indigo des Indes'),
('Indigo fond de cuve'),
('Indigo Maya'),
('Jaune de Taïoukht'),
('Ocre grise'),
('Ocre grise de Roussillon'),
('Ocre jaune de Roussillon'),
('Pastel Blanc de titane Sennelier'),
('Pastel Bleu cobalt Sennelier'),
('Pastel Bleu Turquoise Sennelier'),
('Pastel Indigo Sennelier'),
('Pastel Jaune primaire Sennelier'),
('Pastel Orange Sennelier'),
('Pastel Rouge Hélios Sennelier'),
('Pastel Turquoise Sennelier'),
('Pierre noire'),
('Rose Magenta'),
('Sinopia'),
('Terre d''Ombrie'),
('Terre d''Ombrie calcinée'),
('Terre d''Ombrie naturelle'),
('Terre de Sienne naturelle'),
('Terre de Sienne véritable'),
('Terre verte de Brentonico'),
('Terre verte de Nicosie'),
('Viridian');
