-- Batch import of pigments
INSERT OR IGNORE INTO collections (name) VALUES
("À l'ombre du papillon"),
("À la dérobée, il va dénouer les ombres"),
("Bleu et quoi d'autre"),
("Chemins de verdure"),
("Dans les mots du silence"),
("En traversant le silence des ombres"),
("Entre la lune qui s'en va et le soleil qui vient"),
("Espaces de silence"),
("Fenêtres"),
("Fusains"),
("Hors série"),
("Indigo et ambre"),
("Indigos"),
("Instemps prélevés"),
("L'ombre d'un rêve"),
("La brèche de l'air"),
("La Sagesse du vent"),
("Lieux de passages"),
("Mémoire de l'âme"),
("Ombres au creux des silences"),
("Ombres émanantes"),
("Ombres suspendues"),
("Pays Sages"),
("Paysages et arbres"),
("Pierre et vents"),
("Wabi-Sabi");
