-- Batch import of pigments
INSERT OR IGNORE INTO collections (name) VALUES
("Instemps prélevés"),
("Hors série"),
("Chemins de verdure"),
("Pierre et vents"),
("Mémoire de l'âme"),
("La brèche de l'air"),
("Espaces de silence"),
("Ombres suspendues"),
("Ombres au creux des silences"),
("Ombres émanantes"),
("L'ombre d'un rêve"),
("Fusains"),
("Indigos"),
("À l'ombre du papillon"),
("À la dérobée, il va dénouer les ombres"),
("Paysages et arbres"),
("Bleu et quoi d'autre"),
("En traversant le silence des ombres"),
("Indigo et ambre"),
("Pays Sages"),
("Dans les mots du silence"),
("Lieux de passages"),
("La Sagesse du vent"),
("Entre le lune qui s'en va et le soleil qui vient"),
("Fenêtres"),
("Wabi-Sabi");
