-- Clear existing pigments
DELETE FROM pigments;

-- Batch import of pigments
INSERT OR IGNORE INTO pigments (name) VALUES
("Blanc de titane"),
("Bleu des Indes"),
("Bleu Maya"),
("Caput Mortuum"),
("Cendre d''olivier"),
("Cendre de châtaignier"),
("Cendre de cyprès"),
("Cendre de hêtre"),
("Cendre de platane"),
("Cochenille"),
("Cochenille du Maroc"),
("Cochenille du Mexique"),
("Encre de Chine au trainard"),
("Feuille d'or"),
("Fleurée d'indigo"),
("Fusain"),
("Indigo Baphicacanthus"),
("Indigo de Kanagawa"),
("Indigo de la Roque d''Anthéron"),
("Indigo des Indes"),
("Indigo du Mali"),
("Indigo fond de cuve"),
("Indigo Maya"),
("Jaune de Taïoukht"),
("Ocre grise"),
("Ocre grise de Roussillon"),
("Ocre jaune de Roussillon"),
("Ocre rouge de Roussillon"),
("Orange vif du Maroc"),
("Pastel Blanc de titane Sennelier"),
("Pastel Bleu cobalt Sennelier"),
("Pastel Bleu Turquoise Sennelier"),
("Pastel Indigo Sennelier"),
("Pastel Jaune primaire Sennelier"),
("Pastel Orange Sennelier"),
("Pastel Outremer Sennelier"),
("Pastel Rouge Hélios Sennelier"),
("Pastel Rouge Vermillon Sennelier"),
("Pastel Turquoise Sennelier"),
("Pastel Viridian Sennelier"),
("Pierre noire"),
("Pointe sèche"),
("Poussière de fusain"),
("Rose Magenta"),
("Sinopia"),
("Terre d''Ombrie"),
("Terre d''Ombrie calcinée"),
("Terre d''Ombrie naturelle"),
("Terre de Sienne calcinée"),
("Terre de Sienne naturelle"),
("Terre de Sienne véritable"),
("Terre verte de Brentonico"),
("Terre verte de Nicosie");
